### ISSUE TITLE
Access the core library from python

### ISSUE THREAD

**Issue by JieCui1555** [HomerReid/scuff-em#213]
I'm accessing the core library from python. But it report an error as shown below. So I wonder where to add the path. 
`>>> import scuff
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/public/home/jiecui/.local/lib/python2.7/site-packages/scuff.py", line 32, in <module>
    _scuff = swig_import_helper()
  File "/public/home/jiecui/.local/lib/python2.7/site-packages/scuff.py", line 28, in swig_import_helper
    _mod = imp.load_module('_scuff', fp, pathname, description)
ImportError: /public/home/jiecui/scuffem-icc2015/lib/libscuff.so.0: undefined symbol: dpotrf_
>>>
`

**Comment by texnokrates** [comment]
Do you have LAPACK properly installed?
